apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-ui
  labels:
    {{- include "energy-readings.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  replicas: {{ .Values.webUi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web-ui
  template:
    metadata:
      labels:
        {{- include "energy-readings.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web-ui
    spec:
      containers:
        - name: web-ui
          image: "{{ .Values.webUi.image.repository }}:{{ .Values.webUi.image.tag }}"
          imagePullPolicy: {{ .Values.webUi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webUi.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
            {{- toYaml .Values.webUi.resources | nindent 12 }}
