apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ingestion-api
  labels:
    {{- include "energy-readings.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion-api
spec:
  replicas: {{ .Values.ingestionApi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ingestion-api
  template:
    metadata:
      labels:
        {{- include "energy-readings.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ingestion-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001 # appuser created in Dockerfile
      containers:
        - name: ingestion-api
          image: "{{ .Values.ingestionApi.image.repository }}:{{ .Values.ingestionApi.image.tag }}"
          imagePullPolicy: {{ .Values.ingestionApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingestionApi.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.ingestionApi.port | quote }}
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.ingestionApi.resources | nindent 12 }}