apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-processing-service
  labels:
    {{- include "energy-readings.labels" . | nindent 4 }}
    app.kubernetes.io/component: processing-service
spec:
  replicas: {{ .Values.processingService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: processing-service
  template:
    metadata:
      labels:
        {{- include "energy-readings.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: processing-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001 # appuser created in Dockerfile
      containers:
        - name: processing-service
          image: "{{ .Values.processingService.image.repository }}:{{ .Values.processingService.image.tag }}"
          imagePullPolicy: {{ .Values.processingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.processingService.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.processingService.port | quote }}
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: PROCESSING_DEMO_DELAY_MS
              value: {{ .Values.processingService.demoDelayMs | default 0 | quote }}
          livenessProbe:
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.processingService.resources | nindent 12 }}