apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-processing-service
  labels:
    {{- include "energy-readings.labels" . | nindent 4 }}
    app.kubernetes.io/component: processing-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.processingService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: processing-service